/*
HuggingFace-Go-Hub

Testing V1ProviderAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_V1ProviderAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test V1ProviderAPIService ListComputes", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var vendor string
		var region string

		resp, httpRes, err := apiClient.V1ProviderAPI.ListComputes(context.Background(), vendor, region).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V1ProviderAPIService ListComputes_1", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var vendor string
		var region string

		resp, httpRes, err := apiClient.V1ProviderAPI.ListComputes_0(context.Background(), vendor, region).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V1ProviderAPIService ListRegions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var vendor string

		resp, httpRes, err := apiClient.V1ProviderAPI.ListRegions(context.Background(), vendor).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V1ProviderAPIService ListRegions_2", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var vendor string

		resp, httpRes, err := apiClient.V1ProviderAPI.ListRegions_0(context.Background(), vendor).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V1ProviderAPIService ListVendors", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.V1ProviderAPI.ListVendors(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V1ProviderAPIService ListVendors_3", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.V1ProviderAPI.ListVendors_0(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
