/*
HuggingFace-Go-Hub

Testing V2EndpointAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_V2EndpointAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test V2EndpointAPIService CreateEndpoint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.V2EndpointAPI.CreateEndpoint(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService CreateEndpoint_1", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.V2EndpointAPI.CreateEndpoint_0(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService DeleteEndpoint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.DeleteEndpoint(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService DeleteEndpoint_2", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.DeleteEndpoint_0(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService GetEndpoint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.GetEndpoint(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService GetEndpointLogs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.GetEndpointLogs(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService GetEndpointLogs_3", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.GetEndpointLogs_0(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService GetEndpointMetric", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string
		var metric string

		httpRes, err := apiClient.V2EndpointAPI.GetEndpointMetric(context.Background(), namespace, name, metric).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService GetEndpointMetric_4", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string
		var metric string

		httpRes, err := apiClient.V2EndpointAPI.GetEndpointMetric_0(context.Background(), namespace, name, metric).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService GetEndpoint_5", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.GetEndpoint_0(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService ListEndpoint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.V2EndpointAPI.ListEndpoint(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService ListEndpoint_6", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.V2EndpointAPI.ListEndpoint_0(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService PauseEndpoint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.PauseEndpoint(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService PauseEndpoint_7", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.PauseEndpoint_0(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService ResumeEndpoint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.ResumeEndpoint(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService ResumeEndpoint_8", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.ResumeEndpoint_0(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService UpdateEndpoint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.UpdateEndpoint(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test V2EndpointAPIService UpdateEndpoint_9", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.V2EndpointAPI.UpdateEndpoint_0(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
